spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=EVCoOwnership;encrypt=true;trustServerCertificate=true;characterEncoding=UTF-8;sendStringParametersAsUnicode=true
    username: sa
    password: YourStrong!Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        name: JSESSIONID
        path: /
        http-only: true
        secure: false # TODO: set true trong production với HTTPS
        same-site: lax
        max-age: 24h
      timeout: 24h
    encoding:
      charset: UTF-8
      enabled: true
      force: true