###  Test Register API
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "fullName": "Nguyen Vuong",
  "email": "baov1923@example.com",
  "password": "11111111",
  "cccd": "123406089",
  "driverLicense": "A12345",
  "birthday": "2000-05-01",
  "location": "Hanoi"
}

###  Test Login API
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "vuong@example.com",
  "password": "123456"
}
